version: "3.8"

services:
  unify-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unify-controller
    volumes:
      - /mnt/cluster/unify-controller:/config
    environment:
      - PUID=1024
      - PGID=100
      - TZ=US/Central
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
