## docker-compose.calypso.yaml
# Example per-host compose for `calypso` host
services:
  plex:
    image: linuxserver/plex:1.42.2.10156-f737b826c-ls285
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=65537
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/volume1/plex/config:/config
      - /mnt/share/videos/tv:/tv
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    user: 1024:100
    volumes:
      - /mnt/cluster/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
